"""Generate a styled PDF health check report from analysis results using fpdf2."""

from __future__ import annotations

import re
from datetime import datetime, timezone
from io import BytesIO

from fpdf import FPDF

from .models import AnalysisResponse

PBI_CATEGORIES = {"data_model", "dax_quality", "storage_modes", "parallelization", "report_design", "connectivity"}
DBSQL_CATEGORIES = {"dbsql_performance"}

_SEV_COLORS = {
    "error": (220, 38, 38),
    "warning": (217, 119, 6),
    "info": (37, 99, 235),
}
_SEV_BG = {
    "error": (254, 226, 226),
    "warning": (254, 243, 199),
    "info": (219, 234, 254),
}
_IMPACT_COLORS = {
    "high": (220, 38, 38),
    "medium": (217, 119, 6),
    "low": (136, 136, 136),
}
_AI_COLOR = (124, 58, 237)
_AI_BG = (237, 233, 254)


def _score_color(score: float) -> tuple[int, int, int]:
    if score >= 80:
        return (22, 163, 74)
    if score >= 60:
        return (217, 119, 6)
    return (220, 38, 38)


_SANS = "Helvetica"
_MONO = "Courier"

_UNICODE_MAP = str.maketrans({
    "\u2192": "->", "\u2190": "<-", "\u2194": "<->",
    "\u2013": "-", "\u2014": "--",
    "\u2018": "'", "\u2019": "'", "\u201c": '"', "\u201d": '"',
    "\u2022": "*", "\u00b7": "*", "\u2026": "...",
    "\u2265": ">=", "\u2264": "<=", "\u2260": "!=",
    "\u00d7": "x", "\u00f7": "/",
    "\u2713": "[ok]", "\u2717": "[x]", "\u2714": "[ok]", "\u2716": "[x]",
    "\u25cf": "*", "\u25cb": "o", "\u25a0": "#", "\u25a1": "[]",
    "\u00a0": " ",
})


def _sanitize(text: str) -> str:
    """Replace Unicode chars outside latin-1 with safe ASCII alternatives."""
    text = text.translate(_UNICODE_MAP)
    return text.encode("latin-1", errors="replace").decode("latin-1")


class HealthCheckPDF(FPDF):
    generated_at: str = ""

    def header(self):
        pass

    def footer(self):
        self.set_y(-12)
        self.set_font(_SANS, size=7)
        self.set_text_color(140, 140, 140)
        self.cell(0, 5, f"Generated by PBI Health Check Analyser - {self.generated_at}", align="L")
        self.cell(0, 5, f"Page {self.page_no()}/{{nb}}", align="R")


def _sort_findings(findings: list[dict]) -> list[dict]:
    sev_order = {"error": 0, "warning": 1, "info": 2}
    imp_order = {"high": 0, "medium": 1, "low": 2}
    return sorted(
        findings,
        key=lambda f: (sev_order.get(f.get("severity", "info"), 3), imp_order.get(f.get("impact", "medium"), 3)),
    )


def _draw_badge(pdf: HealthCheckPDF, label: str, bg: tuple, fg: tuple, x: float | None = None):
    """Draw a rounded badge at the current position or at x."""
    pdf.set_font(_SANS, "B", 7)
    w = pdf.get_string_width(label.upper()) + 6
    if x is not None:
        pdf.set_x(x)
    cx = pdf.get_x()
    cy = pdf.get_y()
    pdf.set_fill_color(*bg)
    pdf.set_draw_color(*fg)
    pdf.rect(cx, cy, w, 5, round_corners=True, corner_radius=2, style="DF")
    pdf.set_text_color(*fg)
    pdf.set_xy(cx, cy)
    pdf.cell(w, 5, label.upper(), align="C")
    pdf.set_xy(cx + w + 2, cy)


def _draw_score_box(pdf: HealthCheckPDF, score: float, x: float, y: float):
    color = _score_color(score)
    pdf.set_draw_color(*color)
    pdf.set_line_width(0.8)
    box_w, box_h = 32, 22
    pdf.rect(x, y, box_w, box_h, round_corners=True, corner_radius=3, style="D")
    pdf.set_font(_SANS, "B", 22)
    pdf.set_text_color(*color)
    pdf.set_xy(x, y + 2)
    pdf.cell(box_w, 12, str(round(score)), align="C")
    pdf.set_font(_SANS, size=6)
    pdf.set_text_color(100, 100, 100)
    pdf.set_xy(x, y + 14)
    pdf.cell(box_w, 5, "OVERALL SCORE", align="C")
    pdf.set_line_width(0.2)


def _draw_stat_box(pdf: HealthCheckPDF, value: str, label: str, color: tuple, x: float, y: float):
    w, h = 28, 18
    pdf.set_fill_color(245, 245, 245)
    pdf.rect(x, y, w, h, round_corners=True, corner_radius=2, style="F")
    pdf.set_font(_SANS, "B", 13)
    pdf.set_text_color(*color)
    pdf.set_xy(x, y + 2)
    pdf.cell(w, 8, value, align="C")
    pdf.set_font(_SANS, size=6)
    pdf.set_text_color(100, 100, 100)
    pdf.set_xy(x, y + 11)
    pdf.cell(w, 5, label.upper(), align="C")


def _draw_section_heading(pdf: HealthCheckPDF, title: str):
    pdf.set_font(_SANS, "B", 12)
    pdf.set_text_color(26, 26, 46)
    pdf.cell(0, 8, title)
    pdf.ln(8)
    y = pdf.get_y()
    pdf.set_draw_color(224, 224, 224)
    pdf.set_line_width(0.5)
    pdf.line(10, y, 200, y)
    pdf.set_line_width(0.2)
    pdf.ln(3)


def _draw_category_table(pdf: HealthCheckPDF, categories: list[dict]):
    pdf.set_font(_SANS, size=9)
    for cat in categories:
        y = pdf.get_y()
        if y > 270:
            pdf.add_page()
            y = pdf.get_y()

        pdf.set_text_color(26, 26, 46)
        pdf.set_font(_SANS, "B", 9)
        pdf.set_xy(10, y)
        pdf.cell(55, 6, cat["display_name"])

        if cat["assessed"]:
            score = cat["score"]
            bar_x = 66
            bar_w = 60
            bar_h = 4
            bar_y = y + 1

            pdf.set_fill_color(229, 231, 235)
            pdf.rect(bar_x, bar_y, bar_w, bar_h, round_corners=True, corner_radius=1.5, style="F")

            fill_w = max(bar_w * score / 100, 0.5)
            pdf.set_fill_color(*_score_color(score))
            pdf.rect(bar_x, bar_y, fill_w, bar_h, round_corners=True, corner_radius=1.5, style="F")

            pdf.set_font(_SANS, "B", 9)
            pdf.set_text_color(*_score_color(score))
            pdf.set_xy(128, y)
            pdf.cell(15, 6, str(round(score)), align="R")

            n_findings = len(cat.get("findings", []))
            pdf.set_font(_SANS, size=8)
            pdf.set_text_color(100, 100, 100)
            pdf.set_xy(145, y)
            suffix = "s" if n_findings != 1 else ""
            pdf.cell(30, 6, f"{n_findings} finding{suffix}", align="R")
        else:
            pdf.set_font(_SANS, "I", 8)
            pdf.set_text_color(160, 160, 160)
            pdf.set_xy(66, y)
            pdf.cell(60, 6, "Not assessed")

        pdf.set_draw_color(238, 238, 238)
        pdf.line(10, y + 6, 200, y + 6)
        pdf.set_y(y + 7)


def _draw_finding(pdf: HealthCheckPDF, f: dict):
    y_start = pdf.get_y()
    sev = f.get("severity", "info")
    impact = f.get("impact", "medium")
    is_ai = f.get("details", {}).get("source") == "ai_analysis"

    rec = f.get("recommendation", "")
    desc = f.get("description", "")
    rec_parts = _split_code_blocks(rec)
    est_lines = 3 + (len(desc) // 80) + sum(2 + len(p[1].split("\n")) if p[0] == "code" else 1 + len(p[1]) // 80 for p in rec_parts)
    est_height = est_lines * 4.5

    if y_start + est_height > 275:
        pdf.add_page()
        y_start = pdf.get_y()

    pdf.set_draw_color(224, 224, 224)
    card_x = 10
    card_w = 190

    pdf.set_xy(card_x + 3, y_start + 2)
    _draw_badge(pdf, sev, _SEV_BG.get(sev, (230, 230, 230)), _SEV_COLORS.get(sev, (100, 100, 100)))

    pdf.set_font(_SANS, "B", 9)
    pdf.set_text_color(26, 26, 46)
    name_x = pdf.get_x() + 1
    pdf.set_x(name_x)
    pdf.cell(0, 5, _sanitize(f.get("name", "")), align="L")

    imp_color = _IMPACT_COLORS.get(impact, (136, 136, 136))
    pdf.set_font(_SANS, size=7)
    pdf.set_text_color(*imp_color)
    imp_label = f"{impact} impact"
    imp_w = pdf.get_string_width(imp_label) + 4
    pdf.set_xy(card_x + card_w - imp_w - 3, y_start + 2)
    pdf.cell(imp_w, 5, imp_label, align="R")

    if is_ai:
        pdf.set_xy(card_x + card_w - imp_w - 20, y_start + 2)
        _draw_badge(pdf, "AI", _AI_BG, _AI_COLOR)

    pdf.set_xy(card_x + 3, y_start + 9)
    pdf.set_font(_SANS, size=8)
    pdf.set_text_color(68, 68, 68)
    pdf.multi_cell(card_w - 6, 4, _sanitize(desc))

    if rec_parts:
        y_rec = pdf.get_y() + 1
        pdf.set_xy(card_x + 3, y_rec)
        pdf.set_font(_SANS, "B", 6)
        pdf.set_text_color(140, 140, 140)
        pdf.cell(0, 4, "RECOMMENDATION")
        pdf.ln(4)

        for kind, text in rec_parts:
            if kind == "text" and text.strip():
                pdf.set_xy(card_x + 3, pdf.get_y())
                pdf.set_font(_SANS, size=8)
                pdf.set_text_color(26, 26, 46)
                pdf.multi_cell(card_w - 6, 4, _sanitize(text.strip()))
            elif kind == "code" and text.strip():
                code_y = pdf.get_y() + 1
                code_lines = text.strip().split("\n")
                code_h = len(code_lines) * 3.5 + 4
                if code_y + code_h > 280:
                    pdf.add_page()
                    code_y = pdf.get_y()
                pdf.set_fill_color(30, 30, 46)
                pdf.rect(card_x + 3, code_y, card_w - 6, code_h, round_corners=True, corner_radius=2, style="F")
                pdf.set_font(_MONO, size=7)
                pdf.set_text_color(166, 227, 161)
                for i, line in enumerate(code_lines):
                    pdf.set_xy(card_x + 5, code_y + 2 + i * 3.5)
                    pdf.cell(card_w - 10, 3.5, _sanitize(line))
                pdf.set_y(code_y + code_h + 1)

    ref = f.get("reference_url", "")
    if ref:
        pdf.set_xy(card_x + 3, pdf.get_y())
        pdf.set_font(_SANS, size=7)
        pdf.set_text_color(37, 99, 235)
        pdf.cell(0, 4, f"Reference: {ref}", link=ref)
        pdf.ln(4)

    y_end = pdf.get_y() + 2
    pdf.rect(card_x, y_start, card_w, y_end - y_start, round_corners=True, corner_radius=2, style="D")
    pdf.set_y(y_end + 2)


def _split_code_blocks(text: str) -> list[tuple[str, str]]:
    """Split text into alternating ('text', ...) and ('code', ...) segments."""
    parts: list[tuple[str, str]] = []
    remaining = text
    while remaining:
        m = re.search(r"```(?:\w*\n?)?([\s\S]*?)```", remaining)
        if m:
            before = remaining[: m.start()].strip()
            if before:
                parts.append(("text", before))
            parts.append(("code", m.group(1).strip()))
            remaining = remaining[m.end():]
        else:
            if remaining.strip():
                parts.append(("text", remaining.strip()))
            break
    return parts


def _draw_qp_banner(pdf: HealthCheckPDF, qps: dict):
    y = pdf.get_y()
    if y > 255:
        pdf.add_page()
        y = pdf.get_y()

    banner_h = 28
    if qps.get("tables_scanned"):
        banner_h += 6

    pdf.set_fill_color(239, 246, 255)
    pdf.set_draw_color(191, 219, 254)
    pdf.rect(10, y, 190, banner_h, round_corners=True, corner_radius=2, style="DF")

    pdf.set_xy(13, y + 2)
    pdf.set_font(_SANS, "B", 9)
    pdf.set_text_color(30, 64, 175)
    pdf.cell(50, 5, "Query Profile Analysis")

    bx = pdf.get_x() + 2
    if qps.get("is_pbi_generated"):
        pdf.set_xy(bx, y + 2)
        _draw_badge(pdf, "PBI Generated", (219, 234, 254), (30, 64, 175))
        bx = pdf.get_x() + 2
    if qps.get("has_llm_analysis"):
        pdf.set_xy(bx, y + 2)
        _draw_badge(pdf, "AI Analysis", _AI_BG, _AI_COLOR)

    metrics = [
        ("Total Time", f"{qps.get('total_time_ms', 0) / 1000:.1f}s"),
        ("Data Read", f"{qps.get('read_bytes', 0) / 1048576:.1f} MB"),
        ("Rows Read", f"{qps.get('rows_read', 0):,}"),
        ("Rows Produced", f"{qps.get('rows_produced', 0):,}"),
    ]
    mx = 13
    for label, val in metrics:
        pdf.set_xy(mx, y + 10)
        pdf.set_font(_SANS, size=6)
        pdf.set_text_color(100, 100, 100)
        pdf.cell(35, 4, label.upper())
        pdf.set_xy(mx, y + 14)
        pdf.set_font(_SANS, "B", 10)
        pdf.set_text_color(30, 64, 175)
        pdf.cell(35, 5, val)
        mx += 45

    if qps.get("tables_scanned"):
        pdf.set_xy(13, y + 22)
        pdf.set_font(_SANS, "B", 7)
        pdf.set_text_color(30, 64, 175)
        pdf.cell(12, 4, "Tables:")
        pdf.set_font(_SANS, size=7)
        pdf.cell(0, 4, ", ".join(qps["tables_scanned"]))

    pdf.set_y(y + banner_h + 4)


def generate_pdf(data: AnalysisResponse) -> bytes:
    """Render analysis results into a styled PDF report. Returns PDF bytes."""
    data_dict = data.model_dump()
    report = data_dict["report"]

    all_findings: list[dict] = []
    for cat in report["categories"]:
        for f in cat.get("findings", []):
            f["_category"] = cat["category"]
            all_findings.append(f)

    pbi_findings = _sort_findings([f for f in all_findings if f["_category"] in PBI_CATEGORIES])
    dbsql_findings = _sort_findings([f for f in all_findings if f["_category"] in DBSQL_CATEGORIES])
    ai_count = sum(1 for f in all_findings if f.get("details", {}).get("source") == "ai_analysis")

    pdf = HealthCheckPDF(orientation="P", unit="mm", format="A4")
    pdf.generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    pdf.alias_nb_pages()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()

    # --- Title & score ---
    pdf.set_font(_SANS, "B", 18)
    pdf.set_text_color(26, 26, 46)
    pdf.cell(150, 10, "Power BI Health Check Report")

    _draw_score_box(pdf, report["overall_score"], 168, pdf.get_y())
    pdf.ln(10)

    subtitle_parts = [data_dict.get("model_name", "")]
    if data_dict.get("tables_count", 0) > 0:
        subtitle_parts.append(f"{data_dict['tables_count']} tables")
        subtitle_parts.append(f"{data_dict['relationships_count']} relationships")
        subtitle_parts.append(f"{data_dict['measures_count']} measures")
    if data_dict.get("query_profile_summary"):
        subtitle_parts.append("query profile analyzed")
    subtitle_parts.append(f"Mode: {report['mode']}")

    pdf.set_font(_SANS, size=8)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(0, 5, _sanitize(" - ".join(subtitle_parts)))
    pdf.ln(8)

    # --- Summary stats ---
    stats_y = pdf.get_y()
    stat_x = 10
    stats = [
        (str(report["error_count"]), "Errors", (220, 38, 38)),
        (str(report["warning_count"]), "Warnings", (217, 119, 6)),
        (str(report["info_count"]), "Info", (37, 99, 235)),
        (str(report["total_findings"]), "Total", (26, 26, 46)),
    ]
    if ai_count > 0:
        stats.append((str(ai_count), "AI Insights", _AI_COLOR))

    for val, label, color in stats:
        _draw_stat_box(pdf, val, label, color, stat_x, stats_y)
        stat_x += 32
    pdf.set_y(stats_y + 22)

    # --- Category scores ---
    _draw_section_heading(pdf, "Category Scores")
    _draw_category_table(pdf, report["categories"])
    pdf.ln(3)

    # --- Query profile banner ---
    qps = data_dict.get("query_profile_summary")
    if qps:
        _draw_qp_banner(pdf, qps)

    # --- Parse warnings ---
    warnings = data_dict.get("parse_warnings") or []
    if warnings:
        pdf.set_font(_SANS, "B", 8)
        pdf.set_text_color(180, 120, 0)
        pdf.cell(0, 5, "Parse Warnings:")
        pdf.ln(4)
        pdf.set_font(_SANS, size=7)
        for w in warnings:
            pdf.cell(5, 4, "·")
            pdf.cell(0, 4, w)
            pdf.ln(4)
        pdf.ln(2)

    # --- PBI findings ---
    if pbi_findings:
        _draw_section_heading(pdf, "Power BI Model Findings")
        for f in pbi_findings:
            _draw_finding(pdf, f)

    # --- DBSQL findings ---
    if dbsql_findings:
        if pbi_findings:
            pdf.add_page()
        _draw_section_heading(pdf, "Databricks SQL Findings")
        for f in dbsql_findings:
            _draw_finding(pdf, f)

    buf = BytesIO()
    pdf.output(buf)
    return buf.getvalue()
