"""Databricks SQL performance checks (works on live data or uploaded JSON)."""

from __future__ import annotations

import hashlib
import re
from collections import Counter

from ...parsers.models import Finding, Impact, QueryHistoryData, Severity


def _normalize_query(sql: str) -> str:
    """Normalize a SQL query for deduplication (strip whitespace, literals)."""
    sql = re.sub(r"--.*$", "", sql, flags=re.MULTILINE)
    sql = re.sub(r"\s+", " ", sql).strip().lower()
    sql = re.sub(r"'[^']*'", "'?'", sql)
    sql = re.sub(r"\b\d+\b", "?", sql)
    return sql


def _is_pbi_query(sql: str) -> bool:
    """Detect if a SQL query was generated by Power BI."""
    indicators = [
        "`OTBL`",
        "`ITBL`",
        "as `OTBL`",
        "as `ITBL`",
        "TOP ",
        "OUTER APPLY",
    ]
    return any(indicator.lower() in sql.lower() for indicator in indicators)


def run_dbsql_checks(query_data: QueryHistoryData, thresholds: dict) -> list[Finding]:
    findings: list[Finding] = []

    if not query_data.queries:
        return findings

    successful = [q for q in query_data.queries if q.status.lower() in ("finished", "ok", "success", "")]
    failed = [q for q in query_data.queries if q.status.lower() in ("failed", "error", "canceled")]

    # Failed queries
    if failed:
        error_msgs = [q.error_message for q in failed[:5] if q.error_message]
        findings.append(Finding(
            rule_id="dbsql_query_errors",
            category="dbsql_performance",
            name="Failed Queries Detected",
            severity=Severity.ERROR,
            description=f"{len(failed)} out of {len(query_data.queries)} queries failed",
            recommendation="Review error messages and check schema alignment.",
            impact=Impact.HIGH,
            details={
                "failed_count": len(failed),
                "total_count": len(query_data.queries),
                "sample_errors": error_msgs[:3],
            },
        ))

    # Slow queries
    if successful:
        durations = sorted([q.duration_seconds for q in successful])
        p95_idx = int(len(durations) * 0.95)
        p95 = durations[min(p95_idx, len(durations) - 1)]
        avg_duration = sum(durations) / len(durations)
        threshold_secs = thresholds.get("dbsql_slow_queries", {}).get("p95_seconds", 10)

        if p95 > threshold_secs:
            slow_queries = [q for q in successful if q.duration_seconds > threshold_secs]
            findings.append(Finding(
                rule_id="dbsql_slow_queries",
                category="dbsql_performance",
                name="Slow Queries Detected",
                severity=Severity.WARNING,
                description=(
                    f"P95 latency is {p95:.1f}s (threshold: {threshold_secs}s). "
                    f"{len(slow_queries)} queries exceed threshold. "
                    f"Average: {avg_duration:.1f}s"
                ),
                recommendation=(
                    "Investigate via Query Profiles. Common fixes: ANALYZE TABLE, "
                    "OPTIMIZE, liquid clustering, or materialized views."
                ),
                impact=Impact.HIGH,
                details={
                    "p95_seconds": round(p95, 2),
                    "avg_seconds": round(avg_duration, 2),
                    "slow_count": len(slow_queries),
                },
            ))

    # Duplicate/similar queries
    normalized_counts: Counter[str] = Counter()
    query_examples: dict[str, str] = {}
    for q in successful:
        if not q.query_text:
            continue
        norm = _normalize_query(q.query_text)
        h = hashlib.md5(norm.encode()).hexdigest()
        normalized_counts[h] += 1
        if h not in query_examples:
            query_examples[h] = q.query_text[:200]

    duplicates = {h: count for h, count in normalized_counts.items() if count > 3}
    if duplicates:
        total_dup_executions = sum(duplicates.values())
        findings.append(Finding(
            rule_id="dbsql_duplicate_queries",
            category="dbsql_performance",
            name="Duplicate/Similar Queries",
            severity=Severity.WARNING,
            description=(
                f"{len(duplicates)} distinct query patterns executed {total_dup_executions} times total. "
                f"Visuals may be generating redundant SQL."
            ),
            recommendation=(
                "Consolidate visuals or use user-defined aggregations to reduce "
                "duplicate query execution."
            ),
            impact=Impact.HIGH,
            reference_url="https://github.com/databricks-solutions/power-bi-on-databricks-quickstarts/tree/main/05.%20User-defined%20Aggregations",
            details={
                "duplicate_patterns": len(duplicates),
                "total_executions": total_dup_executions,
                "top_samples": [
                    query_examples[h]
                    for h in sorted(duplicates, key=duplicates.get, reverse=True)[:3]  # type: ignore[arg-type]
                ],
            },
        ))

    # High row scans
    max_rows = thresholds.get("dbsql_high_row_scans", {}).get("max_rows_read", 10_000_000)
    heavy_scans = [q for q in successful if q.rows_read > max_rows]
    if heavy_scans:
        pbi_heavy = [q for q in heavy_scans if _is_pbi_query(q.query_text)]
        findings.append(Finding(
            rule_id="dbsql_high_row_scans",
            category="dbsql_performance",
            name="Queries Scanning Excessive Rows",
            severity=Severity.WARNING,
            description=(
                f"{len(heavy_scans)} queries read more than {max_rows:,} rows. "
                f"{len(pbi_heavy)} appear to be Power BI-generated."
            ),
            recommendation=(
                "Create materialized views or aggregate tables. Add PK constraints "
                "with RELY for join elimination."
            ),
            impact=Impact.HIGH,
            reference_url="https://github.com/databricks-solutions/power-bi-on-databricks-quickstarts/tree/main/07.%20Query%20optimization%20using%20PK",
            details={
                "heavy_scan_count": len(heavy_scans),
                "pbi_heavy_count": len(pbi_heavy),
                "max_rows_read": max(q.rows_read for q in heavy_scans),
            },
        ))

    return findings
