"""LLM-powered M Query to SQL translator for steps the heuristic engine can't handle."""

from __future__ import annotations

import asyncio
import json
import logging
import os

from databricks.sdk.service.serving import ChatMessage, ChatMessageRole

logger = logging.getLogger(__name__)

DEFAULT_ENDPOINT = "databricks-claude-opus-4-6"
ENV_ENDPOINT_KEY = "PBIANALYZER_LLM_ENDPOINT"

SYSTEM_PROMPT = """\
You are an expert in both Power Query M language and Databricks SQL. Your task is to translate \
Power Query M expressions into equivalent Databricks SQL.

You will receive a table's complete M query and a list of specific steps that could not be \
auto-converted by the heuristic engine. For each step, generate the equivalent SQL fragment.

## Rules

1. Output valid Databricks SQL (Spark SQL dialect)
2. Use standard SQL functions — no UDFs
3. For PIVOT: use Databricks SQL PIVOT syntax
4. For UNPIVOT: use UNPIVOT or LATERAL VIEW + STACK
5. For FillDown/FillUp: use window functions (LAST_VALUE / FIRST_VALUE with IGNORE NULLS)
6. For Table.Combine: use UNION ALL
7. For complex `each` expressions: translate M functions to SQL equivalents
8. If a step truly cannot be expressed in SQL, set "sql" to null and explain why in "notes"
9. Reference columns by their SQL-safe names (backtick-wrap if spaces/special chars)
10. The generated SQL should work as part of a SELECT statement or CTE

## M → SQL Function Reference

| M Function | SQL Equivalent |
|------------|---------------|
| Text.Upper | UPPER |
| Text.Lower | LOWER |
| Text.Trim | TRIM |
| Text.Start | LEFT |
| Text.End | RIGHT |
| Text.Contains | CONTAINS / LIKE |
| Text.Replace | REPLACE |
| Text.Length | LENGTH |
| Text.Combine | CONCAT / CONCAT_WS |
| Number.Round | ROUND |
| Number.Abs | ABS |
| Date.Year | YEAR |
| Date.Month | MONTH |
| Date.Day | DAY |
| Date.AddDays | DATE_ADD |
| Date.AddMonths | ADD_MONTHS |
| Date.From | CAST(x AS DATE) |
| DateTime.From | CAST(x AS TIMESTAMP) |
| List.Sum | SUM (as aggregate) |
| List.Average | AVG (as aggregate) |
| List.Count | COUNT (as aggregate) |
| List.Min | MIN (as aggregate) |
| List.Max | MAX (as aggregate) |
| Table.RowCount | COUNT(*) |
| if...then...else | CASE WHEN...THEN...ELSE...END |
| & (string concat) | CONCAT or || |
| null | NULL |
| each [Col] | Direct column reference |

## Output Format

Return a JSON array with one object per step. Each object must have:
- "step_name": the M step name (string)
- "sql": the SQL translation (string or null if impossible)
- "sql_type": one of "select_expr", "where", "join", "group_by", "cte", "full_query" — \
  indicates how this SQL should be composed into the final statement
- "notes": explanation of the translation or why it couldn't be done (string)
- "confidence": "high", "medium", or "low"

Return ONLY the JSON array, no other text."""


async def translate_m_steps_with_llm(
    table_name: str,
    full_m_query: str,
    steps_to_translate: list[dict],
    source_fqn: str = "",
    heuristic_sql: str = "",
    endpoint_name: str | None = None,
) -> list[dict]:
    """Call LLM to translate M steps that the heuristic engine couldn't handle.

    Args:
        table_name: PBI table name
        full_m_query: Complete M expression for context
        steps_to_translate: List of {name, expression, step_type} dicts for unconverted steps
        source_fqn: Fully qualified source table name
        heuristic_sql: SQL generated by heuristic pass (for context)
        endpoint_name: Serving endpoint name

    Returns:
        List of {step_name, sql, sql_type, notes, confidence} dicts
    """
    endpoint = endpoint_name or os.environ.get(ENV_ENDPOINT_KEY, DEFAULT_ENDPOINT)

    user_content = _build_user_prompt(
        table_name, full_m_query, steps_to_translate, source_fqn, heuristic_sql
    )

    messages = [
        ChatMessage(role=ChatMessageRole.SYSTEM, content=SYSTEM_PROMPT),
        ChatMessage(role=ChatMessageRole.USER, content=user_content),
    ]

    try:
        response_text = await _call_endpoint(endpoint, messages)
        return _parse_response(response_text)
    except Exception as exc:
        logger.warning("LLM M translation failed for %s: %s", table_name, exc)
        return [{
            "step_name": s.get("name", "unknown"),
            "sql": None,
            "sql_type": "unknown",
            "notes": f"AI translation unavailable: {exc}",
            "confidence": "none",
        } for s in steps_to_translate]


async def enhance_full_query_with_llm(
    table_name: str,
    full_m_query: str,
    heuristic_sql: str,
    source_fqn: str = "",
    endpoint_name: str | None = None,
) -> dict:
    """Ask the LLM to review and improve the full heuristic SQL translation.

    Returns a dict with:
        - "enhanced_sql": improved SQL (or original if no improvement)
        - "changes": list of changes made
        - "confidence": overall confidence
    """
    endpoint = endpoint_name or os.environ.get(ENV_ENDPOINT_KEY, DEFAULT_ENDPOINT)

    user_content = f"""## Review & Enhance SQL Translation

**Table:** {table_name}
**Source:** {source_fqn}

### Original M Query:
```powerquery
{full_m_query}
```

### Heuristic SQL Translation:
```sql
{heuristic_sql}
```

Review the heuristic SQL translation against the original M query. If the SQL is already correct \
and complete, return it unchanged. If there are improvements needed (missing transformations, \
incorrect logic, missing column renames, type casts not applied, etc.), return the corrected SQL.

Return a JSON object with:
- "enhanced_sql": the improved SQL statement (or the original if already correct)
- "changes": array of strings describing each change made (empty if no changes)
- "confidence": "high", "medium", or "low"
- "is_complete": boolean — true if the SQL fully represents the M query

Return ONLY the JSON object, no other text."""

    messages = [
        ChatMessage(role=ChatMessageRole.SYSTEM, content=SYSTEM_PROMPT),
        ChatMessage(role=ChatMessageRole.USER, content=user_content),
    ]

    try:
        response_text = await _call_endpoint(endpoint, messages)
        return _parse_enhancement(response_text, heuristic_sql)
    except Exception as exc:
        logger.warning("LLM enhancement failed for %s: %s", table_name, exc)
        return {
            "enhanced_sql": heuristic_sql,
            "changes": [],
            "confidence": "none",
            "is_complete": False,
            "error": str(exc),
        }


def _build_user_prompt(
    table_name: str,
    full_m_query: str,
    steps: list[dict],
    source_fqn: str,
    heuristic_sql: str,
) -> str:
    lines = [
        f"## Table: {table_name}",
        f"**Source table:** {source_fqn}" if source_fqn else "",
        "",
        "### Complete M Query (for context):",
        "```powerquery",
        full_m_query,
        "```",
        "",
    ]

    if heuristic_sql:
        lines.extend([
            "### Heuristic SQL (already generated for auto-converted steps):",
            "```sql",
            heuristic_sql,
            "```",
            "",
        ])

    lines.append("### Steps requiring AI translation:")
    lines.append("")
    for i, step in enumerate(steps, 1):
        lines.append(f"**Step {i}: `{step.get('name', 'unknown')}`** (type: {step.get('step_type', 'unknown')})")
        lines.append("```powerquery")
        lines.append(step.get("expression", ""))
        lines.append("```")
        lines.append("")

    lines.append("Translate each step to Databricks SQL. Consider the full M query context "
                 "when translating — earlier steps may affect column names or types.")

    return "\n".join(lines)


async def _call_endpoint(endpoint: str, messages: list[ChatMessage]) -> str:
    from databricks.sdk import WorkspaceClient

    ws = WorkspaceClient()
    response = await asyncio.to_thread(
        ws.serving_endpoints.query,
        name=endpoint,
        messages=messages,
        max_tokens=4096,
        temperature=0.1,
    )

    if hasattr(response, "choices") and response.choices:
        choice = response.choices[0]
        if hasattr(choice, "message") and hasattr(choice.message, "content"):
            return choice.message.content or ""

    if isinstance(response, dict):
        choices = response.get("choices", [])
        if choices and isinstance(choices[0], dict):
            return choices[0].get("message", {}).get("content", "")

    raise ValueError(f"Unexpected response format: {type(response)}")


def _parse_response(text: str) -> list[dict]:
    """Parse LLM response into step translation dicts."""
    text = text.strip()
    if text.startswith("```"):
        lines = text.split("\n")
        lines = [l for l in lines if not l.strip().startswith("```")]
        text = "\n".join(lines)

    items = _try_parse_json(text)
    if items is None:
        logger.warning("Could not parse LLM M translation response: %s", text[:300])
        return []

    if not isinstance(items, list):
        items = [items]

    results = []
    for item in items:
        if not isinstance(item, dict):
            continue
        results.append({
            "step_name": item.get("step_name", "unknown"),
            "sql": item.get("sql"),
            "sql_type": item.get("sql_type", "select_expr"),
            "notes": item.get("notes", ""),
            "confidence": item.get("confidence", "medium"),
        })
    return results


def _parse_enhancement(text: str, fallback_sql: str) -> dict:
    """Parse LLM enhancement response."""
    text = text.strip()
    if text.startswith("```"):
        lines = text.split("\n")
        lines = [l for l in lines if not l.strip().startswith("```")]
        text = "\n".join(lines)

    obj = _try_parse_json(text)
    if obj is None or not isinstance(obj, dict):
        return {
            "enhanced_sql": fallback_sql,
            "changes": [],
            "confidence": "none",
            "is_complete": False,
        }

    return {
        "enhanced_sql": obj.get("enhanced_sql", fallback_sql),
        "changes": obj.get("changes", []),
        "confidence": obj.get("confidence", "medium"),
        "is_complete": obj.get("is_complete", False),
    }


def _try_parse_json(text: str):
    """Try to parse JSON with multiple fallback strategies."""
    try:
        return json.loads(text)
    except json.JSONDecodeError:
        pass

    for start_char, end_char in [("[", "]"), ("{", "}")]:
        start = text.find(start_char)
        end = text.rfind(end_char)
        if start >= 0 and end > start:
            try:
                return json.loads(text[start:end + 1])
            except json.JSONDecodeError:
                pass

    start = text.find("[")
    if start >= 0:
        fragment = text[start:]
        for repair in ["]", "}]", "\"}]", "\"}  }]"]:
            try:
                result = json.loads(fragment + repair)
                if isinstance(result, list):
                    result = [i for i in result if isinstance(i, dict)]
                    if result:
                        return result
            except json.JSONDecodeError:
                continue

    return None
